export const ERP_MODULES = [
  {
    id: 'purchase',
    name: 'Purchase & Procurement',
    sections: [
      { id: 'material-requisition', name: 'Material Requisition' },
      { id: 'indent', name: 'Indent' },
      { id: 'enquiry', name: 'Enquiry' },
      { id: 'quotation', name: 'Quotation' },
      { id: 'comparison', name: 'Quotation Comparison' },
      { id: 'purchase-order', name: 'Purchase Order' },
      { id: 'po-send', name: 'PO Send To Party' },
      { id: 'grn', name: 'GRN' },
      { id: 'transfer-grn', name: 'GRN From Transfer' },
      { id: 'production-grn', name: 'GRN From Production' },
      { id: 'purchase-bill', name: 'Purchase Bill' },
      { id: 'credit-note', name: 'Credit Note' },
      { id: 'debit-note', name: 'Debit Note' },
      { id: 'bill-manage', name: 'Bill Wise Manage' },
      { id: 'payment-request', name: 'Payment Request' },
      { id: 'payment', name: 'Payment' },
    ]
  },
  {
    id: 'inventory',
    name: 'Inventory & Store',
    sections: [
      { id: 'min', name: 'MIN (Issue Note)' },
      { id: 'stock-balance', name: 'Stock Balance' },
      { id: 'consumption', name: 'Project Consumption' },
      { id: 'cost-work', name: 'Select Cost Work' },
      { id: 'other-consumption', name: 'Other Consumption' },
      { id: 'to-party', name: 'To Party' },
      { id: 'crn', name: 'CRN' },
      { id: 'dbn', name: 'DBN' },
      { id: 'vehicle-issue', name: 'Vehicle Issue' },
      { id: 'group-settings', name: 'Item Group Setting' },
      { id: 'job-service', name: 'Job Card Service' },
      { id: 'transfer', name: 'Transfer To Location' },
      { id: 'pending-grn', name: 'Pending GRN' },
      { id: 'log-book', name: 'Log Book' },
      { id: 'breakdown', name: 'Break Down' },
      { id: 'idle-entry', name: 'Idle Entry' },
      { id: 'work-book', name: 'Work Book' },
      { id: 'job-sheet', name: 'Job Sheet' },
      { id: 'mr', name: 'MR' },
      { id: 'working-bill', name: 'Working Bill' },
    ]
  },
  {
    id: 'hr',
    name: 'Human Capital (HR)',
    sections: [
      { id: 'employee-creation', name: 'Employee Creation' },
      { id: 'salary-structure', name: 'Salary Structure' },
      { id: 'earnings', name: 'Earning Heads' },
      { id: 'deductions', name: 'Deduction Heads' },
      { id: 'leave-master', name: 'Leave Master' },
      { id: 'holiday', name: 'Holiday/Weekoff' },
      { id: 'leave-opening', name: 'Leave Opening' },
      { id: 'leave-allotment', name: 'Leave Allotment' },
      { id: 'leave-application', name: 'Leave Application' },
      { id: 'attendance', name: 'Attendance Entry' },
      { id: 'overtime', name: 'Overtime Request' },
      { id: 'on-duty', name: 'On Duty Request' },
      { id: 'salary-compute', name: 'Salary Calculation' },
      { id: 'other-addition', name: 'Other Addition' },
      { id: 'loan-advance', name: 'Loan & Advance' },
      { id: 'other-deduction', name: 'Other Deduction' },
      { id: 'posting', name: 'Salary A/C Posting' },
      { id: 'view', name: 'Employee View' },
    ]
  },
  {
    id: 'machinery',
    name: 'Machinery & Assets',
    sections: [
      { id: 'machine-list', name: 'Machine List' },
      { id: 'log-book', name: 'Log Book' },
      { id: 'work-book', name: 'Work Book' },
      { id: 'idle-entry', name: 'Idle Entry' },
      { id: 'breakdown', name: 'Break Down' },
      { id: 'hire-given', name: 'Hire Given' },
      { id: 'hire-taken', name: 'Hire Taken' },
      { id: 'work-order', name: 'Work Order' },
      { id: 'hire-contract', name: 'Hire Contract' },
      { id: 'working-bill', name: 'Working Bill' },
      { id: 'maintenance', name: 'Maintenance Job Sheet' },
      { id: 'mr-creation', name: 'MR Creation' },
      { id: 'store-issue', name: 'Store Issue' },
      { id: 'maintenance-min', name: 'Maintenance MIN' },
      { id: 'service-bill', name: 'Job Card Service Bill' },
      { id: 'pl', name: 'Machinery P&L' },
    ]
  },
  {
    id: 'project',
    name: 'Project Management',
    sections: [
      { id: 'project-master', name: 'Project Master' },
      { id: 'wbs', name: 'WBS Road Structure' },
      { id: 'boq', name: 'BOQ Creation' },
      { id: 'planning', name: 'Planning Module' },
      { id: 'execution-type', name: 'Execution Type' },
      { id: 'work-order', name: 'Work Order' },
      { id: 'dpr', name: 'Daily Progress Report' },
      { id: 'planned-vs-achieved', name: 'Planned vs Achieved' },
      { id: 'sub-contractor-bill', name: 'Sub-Contractor Bill' },
      { id: 'running-account-bill', name: 'Running Account (RA) Bill' },
      { id: 'ac-posting', name: 'A/C Posting — Accounting' }
    ]
  },
  {
    id: 'production',
    name: 'Production Flow',
    sections: [
      { id: 'rmc', name: 'RMC' },
      { id: 'bitumen', name: 'Bitumen' },
      { id: 'wmm-gsb', name: 'WMM/GSB' },
      { id: 'crusher', name: 'Crusher Production' },
      { id: 'recipe', name: 'General Recipe' },
      { id: 'challan', name: 'Production Challan' },
      { id: 'stock-update', name: 'Stock Update' },
      { id: 'site-transfer', name: 'Item Transfer To Site' },
      { id: 'party-dispatch', name: 'Item Issue To Party' },
      { id: 'tax-invoice', name: 'MIN Tax Invoice Challan' },
      { id: 'sales-quotation', name: 'Sales Quotation' },
      { id: 'sales-order', name: 'Sales Order' },
      { id: 'schedule', name: 'Schedule Entry' },
      { id: 'challan-entry', name: 'Challan Entry' },
      { id: 'sales-invoice', name: 'Sales Invoice' },
    ]
  },
  {
    id: 'accounts',
    name: 'Accounts & Finance',
    sections: [
      { id: 'purchase-bill', name: 'Purchase Bill' },
      { id: 'purchase-return', name: 'Purchase Return' },
      { id: 'transporter-bill', name: 'Transporter Bill' },
      { id: 'rmc-sales', name: 'RMC Sales' },
      { id: 'sales-gst', name: 'Sales GST' },
      { id: 'salary-voucher', name: 'Salary Voucher' },
      { id: 'advance-loan', name: 'Advance Loan' },
      { id: 'ff-posting', name: 'FF Posting' },
      { id: 'sub-contract-bill', name: 'Sub Contract Bill' },
      { id: 'running-bill', name: 'Running Bill' },
      { id: 'payment-voucher', name: 'Payment Voucher' },
      { id: 'receipt-voucher', name: 'Receipt Voucher' },
      { id: 'journal', name: 'Journal Voucher' },
      { id: 'contra', name: 'Contra Voucher' },
      { id: 'debit', name: 'Debit Note' },
      { id: 'credit', name: 'Credit Note' },
      { id: 'bill-pass', name: 'Bill Pass Payment' },
      { id: 'voucher-approval', name: 'Main Voucher Approval' },
      { id: 'audit', name: 'Audit Voucher' },
      { id: 'gl-bank', name: 'GL Data Bank' },
      { id: 'job-card', name: 'Job Card' },
      { id: 'machine-hire-bill', name: 'Machinery Hire Bill' },
      { id: 'machine-emi', name: 'Machinery EMI' },
      { id: 'machine-insurance', name: 'Machine Insurance' },
      { id: 'machine-fitness', name: 'Machine Fitness' },
      { id: 'machine-permit', name: 'Machine Permit' },
      { id: 'machine-tax', name: 'Machine Taxation' },
      { id: 'machine-welfare', name: 'Machine Welfare' },
      { id: 'machine-puc', name: 'Machine PUC' },
    ]
  },
  {
    id: 'correspondence',
    name: 'Correspondence',
    sections: [
      { id: 'inward', name: 'Letter Inward' },
      { id: 'read', name: 'Letter Read' },
      { id: 'outward', name: 'Letter Outward' },
      { id: 'tribunal', name: 'Arbitration Tribunal' },
      { id: 'proceedings', name: 'Arbitration Proceedings' },
      { id: 'court', name: 'Court Proceedings' },
      { id: 'gate-pass', name: 'Gate Pass' },
      { id: 'out-time', name: 'Out Time' },
      { id: 'message', name: 'Management Message' },
    ]
  },
  {
    id: 'tender',
    name: 'Tender Portal',
    sections: [
      { id: 'nit', name: 'Tender NIT' },
      { id: 'seen', name: 'Tender Seen' },
      { id: 'purchase', name: 'Tender Add Purchase' },
      { id: 'guarantee', name: 'BG/FDR Maintain' },
      { id: 'pre-bid', name: 'Pre Bid Meeting' },
      { id: 'upload', name: 'Tender Document Upload' },
      { id: 'opening', name: 'Tender Opening Update' },
      { id: 'bid', name: 'Enter Bid' },
      { id: 'allotment', name: 'Project Allotment' },
    ]
  }
];
